#!/bin/bash
set -e
# chkconfig: 345 20 80
export BAMBOO_HOME=/opt/bamboo/atlassian-bamboo-5.8.1
#chown -R bamboo:bamboo $BAMBOO_HOME
#echo "bamboo.home=/opt/bamboo/atlassian-bamboo-5.8.1" >> $BAMBOO_HOME/atlassian-bamboo/WEB-INF/classes/bamboo-init.properties

start(){
echo "Starting Bamboo.."
sudo $BAMBOO_HOME/bin/startup.sh
}
stop(){
echo "Stopping Bamboo.."
sudo $BAMBOO_HOME/bin/shutdown.sh 
}
restart(){
stop
sleep 15
start
}
status() {
ps aux | grep -i "bamboo" | grep -v grep
}
case "$1" in
start)
start
;;
stop)
stop
;;
restart)
restart
;;
status)
status
;;
*)
echo "Usage: bamboo {start|stop|restart|status}"
exit 1
esac
exit 0
